#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define SELECT_CONF_MAX 64
#define SELECT_CONF_TIMEOUT 10
#define LOG_CONF_OUTPUT alog
#define UIP_CONF_LL_802154 0
#define UIP_CONF_ND6_DEF_MAXDADNS 0
#define UIP_CONF_BUFFER_SIZE 1500
#define LINKADDR_CONF_SIZE 6

#endif /* PROJECT_CONFIG_H */
