CONTIKI_CPU_DIRS = . net dev

CONTIKI_SOURCEFILES += rtimer-arch.c watchdog.c eeprom.c int-master.c
CONTIKI_SOURCEFILES += gpio-hal-arch.c
CONTIKI_SOURCEFILES += serialport.c

CROSS_COMPILE_PREFIX ?=

### Compiler definitions
CC       = $(CROSS_COMPILE_PREFIX)gcc
ifdef LD_OVERRIDE
  LD     = $(LD_OVERRIDE)
else
  LD     = $(CROSS_COMPILE_PREFIX)gcc
endif
AS       = $(CROSS_COMPILE_PREFIX)as
AR       = $(CROSS_COMPILE_PREFIX)ar
NM       = $(CROSS_COMPILE_PREFIX)nm
OBJCOPY  = $(CROSS_COMPILE_PREFIX)objcopy
STRIP    = $(CROSS_COMPILE_PREFIX)strip
ifeq ($(WERROR),1)
CFLAGSWERROR=-Werror
endif
CFLAGSNO = -Wall -g $(CFLAGSWERROR)
CFLAGS  += $(CFLAGSNO)
CFLAGS  += -ffunction-sections -fdata-sections -fPIC -std=gnu99

### Are we building with code size optimisations?
SMALL ?= 0

# The optimizations on native platform cannot be enabled in GCC (not Clang) versions less than 7.2
GCC_IS_CLANG := $(shell $(CC) --version 2> /dev/null | grep clang)
ifneq ($(GCC_IS_CLANG),)
  NATIVE_CAN_OPTIIMIZE = 1
else
  GCC_VERSION := $(shell $(CC) -dumpfullversion -dumpversion | cut -b1-3)
  ifeq ($(shell expr $(GCC_VERSION) \>= 7.2), 1)
  	NATIVE_CAN_OPTIIMIZE = 1
  else
  	NATIVE_CAN_OPTIIMIZE = 0
  endif
endif

ifeq ($(NATIVE_CAN_OPTIIMIZE),1)
  ifeq ($(SMALL),1)
    CFLAGS += -Os
  else
    CFLAGS += -O2
  endif
endif

ifeq ($(HOST_OS),Darwin)
AROPTS = -rc
LDFLAGS_WERROR := -Wl,-fatal_warnings
LDFLAGS += -Wl,-flat_namespace,-map,$(CONTIKI_NG_PROJECT_MAP)
CFLAGS += -DHAVE_SNPRINTF=1 -U__ASSERT_USE_STDERR
else
ifeq ($(HOST_OS),Linux)
LDFLAGS += -Wl,-Map=$(CONTIKI_NG_PROJECT_MAP) 
LDFLAGS += -Wl,--gc-sections,--sort-section=name -fPIC
endif
ifeq ($(HOST_OS),Android)
LDFLAGS += -Wl,-Map=$(CONTIKI_NG_PROJECT_MAP) 
LDFLAGS += -Wl,--gc-sections,--sort-section=name -fPIC
endif
endif

MAKE_MAC ?= MAKE_MAC_NULLMAC

### Compilation rules

%.so: $(OBJECTDIR)/%.o $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) $(CONTIKI_NG_TARGET_LIB)
	$(TRACE_LD)
	$(Q)$(LD) $(LDFLAGS) -Wl,--version-script=$(subst .so,,$@).version $(TARGET_STARTFILES) ${filter-out %.a,$^} \
		${filter %.a,$^} $(TARGET_LIBFILES) -shared -o $@
